<?php

return [
	// 'base_url' => 'http://giaothuong.langnghedulichhoanghoa.vn/',
	'base_url' => 'http://giaothuong.vn/',
	'role' => [
		1 => 'Tạo mới thành viên',
		2 => 'Thay đổi thành viên',
		3 => 'Xóa thành viên',
		4 => 'Xem thành viên',
		5 => 'Tạo mới sản phẩm',
		6 => 'Thay đổi sản phẩm',
		7 => 'Xóa sản phẩm',
		8 => 'Xem sản phẩm',
		9 => 'Tạo mới cơ sở',
		10 => 'Thay đổi cơ sở',
		11 => 'Xóa cơ sở',
		12 => 'Xem cơ sở',
		13 => 'Tạo mới tin đăng',
		14 => 'Thay đổi tin đăng',
		15 => 'Xóa tin đăng',
		16 => 'Xem tin đăng',
		17 => 'Tạo mới bài viết',
		18 => 'Thay đổi bài viết',
		19 => 'Xóa bài viết',
		20 => 'Xem bài viết',
		21 => 'Tạo mới tài nguyên Website',
		22 => 'Thay đổi tài nguyên Website',
		23 => 'Xóa tài nguyên Website',
		24 => 'Xem tài nguyên Website',
		25 => 'Tạo mới qtv',
		26 => 'Thay đổi qtv',
		27 => 'Xóa qtv',
		28 => 'Xem qtv',
		29 => 'Tạo mới liên hệ',
		30 => 'Thay đổi liên hệ',
		31 => 'Xóa liên hệ',
		32 => 'Xem liên hệ',
		33 => 'Tạo mới thư viện',
		34 => 'Thay đổi thư viện',
		35 => 'Xóa thư viện',
		36 => 'Xem thư viện',
	],
	'types' => [
		'1'=>'Hàng hóa',
		'2'=>'Du lịch',
	],
];